# ============================================================================
#
# BitMagic Library makefile
# (c) 2019 Anatoliy Kuznetsov.
#
# ============================================================================

PROJECTNAME=BitMagic Library Sample

CXXSOURCES=$(wildcard *.cpp)

BASICINCS=src

CSOURCES= 

DESTINATION = svsample07

DESTTYPE = 
DESTINATIONDIR=samples/svsample07

include ../../makefile.in


