# ============================================================================
# BitMagic Library sample makefile
# ============================================================================

PROJECTNAME=BitMagic Library Sample

CXXSOURCES=$(wildcard *.cpp)
BASICINCS=src
CSOURCES=

DESTINATION = sample28
DESTTYPE =
DESTINATIONDIR=samples/bvsample28

include ../../makefile.in
