/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bitmagic_core_SimdUtil0 */

#ifndef _Included_io_bitmagic_core_SimdUtil0
#define _Included_io_bitmagic_core_SimdUtil0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bitmagic_core_SimdUtil0
 * Method:    getLibName0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bitmagic_core_SimdUtil0_getLibName0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
