/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bitmagic_core_BVIterator0 */

#ifndef _Included_io_bitmagic_core_BVIterator0
#define _Included_io_bitmagic_core_BVIterator0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bitmagic_core_BVIterator0
 * Method:    create0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_bitmagic_core_BVIterator0_create0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_core_BVIterator0
 * Method:    dispose0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_bitmagic_core_BVIterator0_dispose0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_core_BVIterator0
 * Method:    isValid0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_bitmagic_core_BVIterator0_isValid0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_core_BVIterator0
 * Method:    get0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_bitmagic_core_BVIterator0_get0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_core_BVIterator0
 * Method:    next0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_bitmagic_core_BVIterator0_next0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
