/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bitmagic_BVector0 */

#ifndef _Included_io_bitmagic_BVector0
#define _Included_io_bitmagic_BVector0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bitmagic_BVector0
 * Method:    init0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_bitmagic_BVector0_init0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    create0
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_bitmagic_BVector0_create0
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    copy0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_bitmagic_BVector0_copy0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    dispose0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_bitmagic_BVector0_dispose0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    version0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bitmagic_BVector0_version0
  (JNIEnv *, jclass);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    copyright0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bitmagic_BVector0_copyright0
  (JNIEnv *, jclass);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    set0
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_bitmagic_BVector0_set0
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    get0
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_bitmagic_BVector0_get0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    getSize0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_bitmagic_BVector0_getSize0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bitmagic_BVector0
 * Method:    setSize0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_bitmagic_BVector0_setSize0
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
