/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tlk00_bitmagic_BVector0 */

#ifndef _Included_org_tlk00_bitmagic_BVector0
#define _Included_org_tlk00_bitmagic_BVector0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tlk00_bitmagic_BVector0
 * Method:    init0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_tlk00_bitmagic_BVector0_init0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_tlk00_bitmagic_BVector0
 * Method:    create0
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_tlk00_bitmagic_BVector0_create0
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_tlk00_bitmagic_BVector0
 * Method:    clone0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_tlk00_bitmagic_BVector0_clone0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_tlk00_bitmagic_BVector0
 * Method:    dispose0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_tlk00_bitmagic_BVector0_dispose0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_tlk00_bitmagic_BVector0
 * Method:    set0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_tlk00_bitmagic_BVector0_set0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_tlk00_bitmagic_BVector0
 * Method:    get0
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tlk00_bitmagic_BVector0_get0
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
