# ============================================================================
#
# BitMagic Library makefile
# (c) 2018 Anatoliy Kuznetsov.
#
# ============================================================================

PROJECTNAME=BitMagic Library Sample

CXXSOURCES=$(wildcard *.cpp)

BASICINCS=src

CSOURCES= 

DESTINATION = svsample06

DESTTYPE = 
DESTINATIONDIR=samples/svsample06

include ../../makefile.in


