# ============================================================================
#
# BitMagic Library makefile
# (c) 2018 Anatoliy Kuznetsov.
#
# ============================================================================

PROJECTNAME=BitMagic Library Sample

CXXSOURCES=$(wildcard *.cpp)

BASICINCS=src

CSOURCES= 

DESTINATION = svsample04

DESTTYPE = 
DESTINATIONDIR=samples/svsample04

include ../../makefile.in


